### PR TITLE
Documentation Update for `v1` Release

### PR DESCRIPTION
**Pull request by otaviof**
# Changes

Updating documentation examples for `v1` tag.

# Submitter Checklist

- [x] ~Includes tests if functionality changed/was added~
- [x] Includes docs if changes are user-facing
- [x] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)  
- [x] Release notes block has been filled in, or marked NONE

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by otaviof** [comment]
/assign @SaschaSchwarze0 

(Thanks in advance!)

**Comment by SaschaSchwarze0** [comment]
@otaviof I forgot our outcome of the versioning discussion. Did we we want to keep the version number in sync with build and cli at least as long as they are in sync or did we conclude that the action has a separate versioning ?

**Comment by otaviof** [comment]
> @otaviof I forgot our outcome of the versioning discussion. Did we we want to keep the version number in sync with build and cli at least as long as they are in sync or did we conclude that the action has a separate versioning ?

I think we discussed releasing both `build` and `cli` in sync, as in using the same release tag. For this repository here, I think we haven't discussed that yet.

However, for the action stand point, it's important to allow different versions for `build ` and `cli`, so different test cases can be created combining those.

**Review by SaschaSchwarze0 — APPROVED** [review]
/lgtm

**Review by SaschaSchwarze0 — APPROVED** [review]
/lgtm

**Pull request merged**
